Código da Equipe: E02
Componentes:
Miguel Bernardino Sousa Borges da Silva; miguel.silva@aln.senaicimatec.edu.br; (71)99956-7589
Felipe Costa Lino Almeida; f.almeida@aln.senaicimatec.edu.br; (71)99986-4321
Guilherme Soares May Rios; guilherme.rios@aln.senaicimatec.edu.br; (71)99958-9990
Daniel Fernandes da Cunha Vasconcelos; daniel.vasconcelos@aln.senaicimatec.edu.br; (71)99934-0512

RELATÓRIO DA ANÁLISE LÉXICA.
Texto fonte analisado: MeuTeste.261

Lexeme: PROGRAM, Código: A25, indiceTabSimb: -, Linha: 3.
Lexeme: MEUPROG, Código: C01, indiceTabSimb: 1, Linha: 3.
Lexeme: DECLARATIONS, Código: A04, indiceTabSimb: -, Linha: 3.
Lexeme: VARTYPE, Código: A36, indiceTabSimb: -, Linha: 10.
Lexeme: REAL, Código: A32, indiceTabSimb: -, Linha: 10.
Lexeme: :, Código: B03, indiceTabSimb: -, Linha: 10.
Lexeme: X1, Código: C01, indiceTabSimb: 2, Linha: 10.
Lexeme: :=, Código: B04, indiceTabSimb: -, Linha: 10.
Lexeme: ;, Código: B01, indiceTabSimb: -, Linha: 10.
Lexeme: VARTYPE, Código: A36, indiceTabSimb: -, Linha: 17.
Lexeme: STRING, Código: A34, indiceTabSimb: -, Linha: 17.
Lexeme: :, Código: B03, indiceTabSimb: -, Linha: 17.
Lexeme: S1, Código: C01, indiceTabSimb: 3, Linha: 17.
Lexeme: :=, Código: B04, indiceTabSimb: -, Linha: 17.
Lexeme: "ABCDEFGHIJKLMNOPQRSTUVWXYZ12", Código: C04, indiceTabSimb: 4, Linha: 17.
Lexeme: ;, Código: B01, indiceTabSimb: -, Linha: 17.
Lexeme: ENDDECLARATIONS, Código: A06, indiceTabSimb: -, Linha: 19.
Lexeme: ENDPROGRAM, Código: A16, indiceTabSimb: -, Linha: 19.