Código da Equipe: E02
Componentes:
Miguel Bernardino Sousa Borges da Silva; miguel.silva@aln.senaicimatec.edu.br; (71)99956-7589
Felipe Costa Lino Almeida; f.almeida@aln.senaicimatec.edu.br; (71)99986-4321
Guilherme Soares May Rios; guilherme.rios@aln.senaicimatec.edu.br; (71)99958-9990
Daniel Fernandes da Cunha Vasconcelos; daniel.vasconcelos@aln.senaicimatec.edu.br; (71)99934-0512

RELATÓRIO DA ANÁLISE LÉXICA.
Texto fonte analisado: MeuTeste.261

Lexeme: PROGRAM, Código: A19, indiceTabSimb: -, Linha: 3.
Lexeme: MEUPROG, Código: C01, indiceTabSimb: 1, Linha: 3.
Lexeme: DECLARATIONS, Código: A04, indiceTabSimb: -, Linha: 3.
Lexeme: VARTYPE, Código: A24, indiceTabSimb: -, Linha: 11.
Lexeme: REAL, Código: A20, indiceTabSimb: -, Linha: 11.
Lexeme: :, Código: B03, indiceTabSimb: -, Linha: 11.
Lexeme: X1, Código: C01, indiceTabSimb: 2, Linha: 11.
Lexeme: :=, Código: B04, indiceTabSimb: -, Linha: 11.
Lexeme: 12345678901234.123456789012345, Código: C07, indiceTabSimb: 3, Linha: 11.
Lexeme: ;, Código: B01, indiceTabSimb: -, Linha: 11.
Lexeme: VARTYPE, Código: A24, indiceTabSimb: -, Linha: 12.
Lexeme: REAL, Código: A20, indiceTabSimb: -, Linha: 12.
Lexeme: :, Código: B03, indiceTabSimb: -, Linha: 12.
Lexeme: M2, Código: C01, indiceTabSimb: 4, Linha: 12.
Lexeme: :=, Código: B04, indiceTabSimb: -, Linha: 12.
Lexeme: "AEDAWDAW", Código: C04, indiceTabSimb: 5, Linha: 12.
Lexeme: 123, Código: C06, indiceTabSimb: 6, Linha: 14.
Lexeme: #, Código: B18, indiceTabSimb: -, Linha: 14.
Lexeme: 456, Código: C06, indiceTabSimb: 7, Linha: 14.
Lexeme: VARTYPE, Código: A24, indiceTabSimb: -, Linha: 21.
Lexeme: STRING, Código: A22, indiceTabSimb: -, Linha: 21.
Lexeme: :, Código: B03, indiceTabSimb: -, Linha: 21.
Lexeme: S1, Código: C01, indiceTabSimb: 8, Linha: 21.
Lexeme: :=, Código: B04, indiceTabSimb: -, Linha: 21.
Lexeme: "ABCDEFGHIJKLMNOPQRSTUVWXYZ12", Código: C04, indiceTabSimb: 9, Linha: 21.
Lexeme: ;, Código: B01, indiceTabSimb: -, Linha: 21.
Lexeme: ENDDECLARATIONS, Código: A06, indiceTabSimb: -, Linha: 25.
Lexeme: ENDPROGRAM, Código: A10, indiceTabSimb: -, Linha: 25.